services:
  frontend:
    restart: unless-stopped
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - global_network

  backend:
    restart: unless-stopped
    build: ./backend
    networks:
      - global_network
    environment:
      - DB_HOST=db
      - DB_NAME=move
      - DB_USER=move
      - DB_PASSWORD=move


  db:
    restart: unless-stopped
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: move
      MYSQL_DATABASE: move
      MYSQL_USER: move
      MYSQL_PASSWORD: move
    volumes:
      - move_db_data:/var/lib/mysql
    networks:
      - global_network


volumes:
  move_db_data:

# ğŸŒ ê¸€ë¡œë²Œ ë„¤íŠ¸ì›Œí¬ (ë‹¤ë¥¸ í”„ë¡œì íŠ¸ì™€ ê³µìœ )
networks:
  global_network:
    external: true